import enum

class InvoiceStatus(str, enum.Enum):
    PROCESSING = "PROCESSING"
    VALIDATED = "VALIDATED"
    WARNING = "WARNING"
    FAILED_EXTRACTION = "FAILED_EXTRACTION"
    CORRUPTED_FILE = "CORRUPTED_FILE"
    APPROVED = "APPROVED"
